source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KrisBlinkingLabel_Example', :exclusive => true do
  pod 'KrisBlinkingLabel', :path => '../'
end

target 'KrisBlinkingLabel_Tests', :exclusive => true do
  pod 'KrisBlinkingLabel', :path => '../'

  
end
